### ISSUE TITLE
Make use of kirby options

### ISSUE THREAD

**Issue by Pascalmh** [fitzage/headid#1]
https://github.com/fitzage/headid/blob/master/headid.php#L7-L8

The `$delete` and `$hyphenate` variables could be set in the site/config/config.php by the user instead of the plugin - see https://getkirby.com/docs/advanced/options.

**Comment by fitzage** [comment]
Hmm…I think what I should do is have defaults that con be overridden by the config file. Which is probably what you're getting at. I don't want to make the user have to set them in the config file if they just want to use the defaults, but I should make it an option.
